#!/usr/bin/env bash

# Custom exports
if [[ "$(mount | grep work)" ]]; then
    export C_WORKDIR="/work";
    export C_ANDROIDWORKDIR="/work/Android";
else
    export C_ANDROIDWORKDIR="${HOME}";
fi
export C_ANDROIDTOOLSDIR="${C_ANDROIDWORKDIR}/tools";
export C_LINEAGEDIR="${C_ANDROIDWORKDIR}/lineage";
export C_PADIR="${C_ANDROIDWORKDIR}/pa";
export C_SUPERRDIR="${C_ANDROIDTOOLSDIR}/superr";
export C_OTHERSTUFFDIR="${C_ANDROIDWORKDIR}/otherstuff";

export EDITOR=nano
export TZ=Asia/Kolkata
export KBUILD_BUILD_USER=ParthB
export USE_CCACHE=1
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export PATH=~/bin:$HOME/.dotfiles/bin:${C_WORKDIR}/bin:${C_ANDROIDTOOLSDIR}/android-studio/Sdk/platform-tools:$PATH

if [[ $HOSTNAME = "build3.de.xda-developers.com" && ! $(command -v zsh) ]]; then
    if [[ $(which zsh) != $SHELL ]]; then
        echo -e "${lightred}ZSH installed but not set as default shell...\nSet \$PATH, \$SHELL in ~/.profile.${nc}"
    fi
fi

# Golang
if [[ -d $C_ANDROIDTOOLSDIR/go ]]; then
    export GOPATH=${C_ANDROIDTOOLSDIR}/go
    export GOBIN=$GOPATH/bin
    export PATH=$GOBIN:$PATH
fi

# Custom aliases
alias shutdown='sudo shutdown -P now'
alias yufastboot='fastboot -i 0x2A96'
alias grepandro='grep -i "\.so\|\.xml\|\.conf\|\.txt\|\.cfg\|\.dat"'
alias setperf='echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias path='echo ${PATH}'
alias superr='cd ${C_SUPERRDIR} && ./superr'
alias jadx='bash ${C_ANDROIDTOOLSDIR}/jadx/build/jadx/bin/jadx-gui'
alias jadx_cli='bash ${C_ANDROIDTOOLSDIR}/jadx/build/jadx/bin/jadx'

alias venv=". $HOME/android/venv/bin/activate"

if [[ -d $C_PADIR ]]; then

    # objdump_aarch64
    if [[ -f ${C_PADIR}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/objdump ]]; then
        alias objdump_aarch64='${C_PADIR}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/objdump'
    else
        alias objdump_aarch64='echo -e "${lightred}objdump file path not found!\nMake sure you have PA source code syned.\nCheck custombashrc for more.${nc}"'
    fi

    # aarch64 toolchain
    if [[ -d "$C_PADIR/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin" ]]; then
        aarch64_tc_bin="$C_PADIR/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin"
    fi


elif [[ -d $C_LINEAGEDIR ]]; then

    # objdump_aarch64
    if [[ -f ${C_LINEAGEDIR}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/objdump ]]; then
        alias objdump_aarch64='${C_LINEAGEDIR}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/objdump'
    else
        alias objdump_aarch64='echo -e "${lightred}objdump file path not found!\nMake sure you have LAOS/PA source code syned.\nCheck custombashrc for more.${nc}"'
    fi

    # aarch64 toolchain
    if [[ -d "$C_LINEAGEDIR/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin" ]]; then
        aarch64_tc_bin="$C_LINEAGEDIR/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin"
    fi

else
    ANDROID_SOURCE_PRESENT="false"
fi
alias makeoutkernel='make O=../out ARCH=arm64 CROSS_COMPILE="${aarch64_tc_bin}/aarch64-linux-android-"'

# ADB
function adbrem() { adb root && adb wait-for-$(adb devices | tail -2 | head -1 | cut -f 2 | sed 's/ *$//g') remount; }
alias adbs='adbrem && adb shell'
alias adbgp='adb shell getprop'
alias adbr='adb reboot'
alias adbpo='adb shell reboot -p'
alias adbrb='adb reboot bootloader'
alias adbrr='adb reboot recovery'
alias adbservice='adb shell service list'
alias adbdumpsys='adb shell dumpsys'
alias adbstrace='adb shell strace'

# Fastboot
alias fbdev='fastboot devices'
alias fbr='fastboot reboot'
alias fbboot='fastboot boot'
alias fbflboot='fastboot flash boot'
alias fbflrec='fastboot flash recovery'

# git
if [[ "$(command -v hub)" ]]; then
    alias git='hub'
fi
alias gtcp='git cherry-pick'
alias grev='git revert'
alias glog='git log --pretty=format:"%h - %an : %s"'
alias gcomgmail='git commit --author="TheStrix <parthbhatia98@gmail.com>"'
alias gcomlaos='git commit --author="TheStrix <parthbhatia@lineageos.org>"'

#------------------------------------------////
# cd-into aliases
#------------------------------------------////
alias dotfiles='cd ~/.dotfiles'
alias laos='cd ${C_LINEAGEDIR}'
alias pa='cd ${C_PADIR}'

# LAOS
alias sagitlaos_d='cd ${C_LINEAGEDIR}/device/xiaomi/sagit'
alias sagitlaod_k='cd ${C_LINEAGEDIR}/kernel/xiaomi/msm8998'
alias sagitloas_v='cd ${C_LINEAGEDIR}/vendor/xiaomi/sagit'

alias kenzolaos_d='cd ${C_LINEAGEDIR}/device/xiaomi/kenzo'
alias kenzolaos_k='cd ${C_LINEAGEDIR}/kernel/xiaomi/msm8956'
alias kenzolaos_v='cd ${C_LINEAGEDIR}/vendor/xiaomi/kenzo'

alias hydrogenlaos_d='cd ${C_LINEAGEDIR}/device/xiaomi/hydrogen'
alias hydrogenlaos_k='cd ${C_LINEAGEDIR}/kernel/xiaomi/msm8956'
alias hydrogenlaos_v='cd ${C_LINEAGEDIR}/vendor/xiaomi/hydrogen'

alias 8956laos_d='cd ${C_LINEAGEDIR}/device/xiaomi/msm8956-common'
alias 8956laos_v='cd ${C_LINEAGEDIR}/vendor/xiaomi/msm8956-common'

alias xiaomilaos_v='cd ${C_LINEAGEDIR}/vendor/xiaomi'

# AOSPA
alias sagitpa_d='cd ${C_PADIR}/device/xiaomi/sagit'
alias sagitpa_k='cd ${C_PADIR}/kernel/xiaomi/msm8998'
alias sagitpa_v='cd ${C_PADIR}/vendor/xiaomi/sagit'

alias xiaomipa_v='cd ${C_PADIR}/vendor/xiaomi'
alias pa_v='cd ${C_PADIR}/vendor/pa'

# Misc
alias superr_cd='cd ${C_SUPERRDIR}'
alias superr_sagit='cd ${C_SUPERRDIR}/superr_sagit'
alias superr_kenzo='cd ${C_SUPERRDIR}/superr_kenzo'
alias superr_hydrogen='cd ${C_SUPERRDIR}/superr_hydrogen' 

# Colors
black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[1;34m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'
