#!/bin/bash

cp bashrcadditions.sh ~/
for f in ~/.bashrc; do
    [ -e "$f" ] && sed -i "\$asource ~/bashrcadditions.sh" ~/.bashrc || sudo sed -i "\$asource ~/bashrcadditions.sh" /etc/bash.bashrc
    break
done

cp -R bin/* $HOME/bin/.
cp -R .zsh* $HOME/.
echo "Done, sourcing the bashrc"
source ~/bashrcadditions.sh
